Використай цей шаблон в роботі з датасетом.      
Ти можеш додавати комірки за потреби, але не змінюй структуру і послідовність питань.      
Обмежся функціями з наведених бібліотек.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

1. Завантаж датасет з бібліотеки seaborn:

In [3]:
df = sns.load_dataset('titanic')

2. Переглянь перші рядки датасету. Зроби висновок, чи коректно він завантажився.

In [4]:
df.head()
#Висновок: використавши функці head(), ми бачимо, що завантажилось перші 5 рядків і ми можемо побачити дані які в нас є')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

3. Перевір типи стовпців. Які з них потребують перетворення?

In [5]:
df.info()
#ось типи які потрібно перетворити:
#- survived: int64 → bool (значення 0/1)
#- pclass: int64 → category (класи 1, 2, 3)
#- sex: object → category (male/female)
#- embarked: object → category (S, C, Q)
#- who: object → category (man/woman/child)
#- embark_town: object → category (назви міст)
#- alive: object → bool (yes/no)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

4. Перевір статистику по УСІМ стовпцям датасету.

In [6]:
df.describe(include = 'all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

5. Необхідно створити єдиний стовпчик, що вказує кількість родичів для кожного пасажира на борту, замість:
- кількість братів/сестер або чоловіків/дружин на борту;
- кількість батьків або дітей на борту;

Булева ознака: стовпчик 'alone'=True, якщо пасажир подорожував один (без родичів на борту).        
Перевір, щоб для одиноких пасажирів новий стовпчик мав значення 0.      
Після створення нового стовпчика, дропни "sibsp", "parch", "alone".     
Результат представ у вигляді підрахунку кількості пропущених значень (NaN) у стовпці relatives.

In [7]:
df['relatives'] = df['sibsp'] + df['parch'] #створила єдиний стовпець родичів
df[df['alone'] == True]['relatives'].unique() #перевірила одиноких користувачів
df = df.drop(columns=["sibsp", "parch", "alone"]) #видалила більше не потрібні стовпці
df['relatives'].isna().sum() #перевірила кількість пропущених значень

np.int64(0)

6. Перевір, як часто зустрічається певна кількість родичів в новому стовпці.    
Результат представ у вигляді таблиці, побудованої з використанням групування та агрегації:

In [8]:
df['relatives'].value_counts().reset_index()

   relatives  count
0          0    537
1          1    161
2          2    102
3          3     29
4          5     22
5          4     15
6          6     12
7         10      7
8          7      6

7. Використовуючи цикл заміни кількість родичів, що перевищує число 5(п'ять) на значення "above 5"(понад п'ять).       
Запиши значення в новий стовпчик ʼrelatives_categoryʼ.     
Результат представ у вигляді таблиці, побудованої з використанням групування та агрегації:

In [9]:
result=[]
for value in df['relatives']:
    if value > 5:
        result.append('above 5')
    else:
        result.append(value) #замінила кількість що перевищує число 5(п'ять) на значення "above 5"
df['relatives_category'] = result
df['relatives_category']
df.groupby('relatives_category').size().reset_index()

  relatives_category    0
0                  0  537
1                  1  161
2                  2  102
3                  3   29
4                  4   15
5                  5   22
6            above 5   25

8. Необхідно вивести на екран статистику по відсотковому показнику пасажирів з кількістю родичів більше 5 відносно загального числа пасажирів для кожного з міст посадки. Для цього:
- порахуй загальну кількість пасажирів в кожному з міст посадки,
- знайди число пасажирів з кількістю родичів більше 5 в кожному з міст посадки,
- поділи ці два стовчики між собою, перетворивши результат у відсотки (ціле число).        
Відобрази статистику порахованих показників, згруповану по містах посадки.

In [10]:
total = df.groupby('embark_town')['relatives'].size() #загальна кількість пасажирів по місту
mask = df[df['relatives']>5] #нова змінна 
above5 = mask.groupby('embark_town')['relatives'].size() #число пасажирів з кількістю родичів більше 5 
perc_relatives = (above5/total * 100).fillna(0).astype(int).reset_index() #відсоток пасажирів з більше 5 родичами по місту
perc_relatives

   embark_town  relatives
0    Cherbourg          0
1   Queenstown          0
2  Southampton          3

9. Заповни відсутні значення віку медіаною.

In [11]:
mediana = df.age.median() #знайшла медіану
df['age'] = df.age.fillna(mediana) #замість пустих значень підставила медіану
df['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

10. Створи новий стовпець, де вік представлено категорією, замість числа (наприклад: до 14 років, 14-34 роки, 35-59 років, 60 і більше років). Виконай задачу з використанням користувацької функції. Осіб з невідомим віком познач відповідно.

In [12]:
def age_category(age): #функція для визначення вікової категорії
    if pd.isna(age):
        return 'невідомий вік'
    elif age < 14:
        return 'до 14 років'
    elif age < 34:
        return '14-34 років'
    elif age < 59:
        return '35-59 років'
    else:
        return '60 і більше років'
df['age_category'] = df['age'].apply(age_category)  #застосування функції до стовпця      
df['age_category']

0      14-34 років
1      35-59 років
2      14-34 років
3      35-59 років
4      35-59 років
          ...
886    14-34 років
887    14-34 років
888    14-34 років
889    14-34 років
890    14-34 років
Name: age_category, Length: 891, dtype: object

11. Перевір, в якій віковій категорії була найвища смертність.     
Для цього рекомендується перетворити стовпець 'alive' в булевий тип.    
 Потім підрахувати загальну кількість пасажирів та кількість тих, хто не вижив.      
 Потім обчисли відносний показниках для кожної категорії.

In [13]:
df['alive'] = df['alive'].map({'yes': True, 'no': False}) #перетворення совпця alive в булевий тип
total = df.groupby('age_category')['alive'].size() #загальна кількість пасажирів по віковій категорії
no_alive = (df['alive'] == False)  #маска для пасажирів які не вижили
dead = df[no_alive].groupby('age_category')['alive'].size()#кількість загиблих по віковій категорії
death_rate = (dead/total * 100).fillna(0).astype(int)  #відсоток смертності по віковій категорії
death_rate #найбільша смертність в категорії 60 і більше років

age_category
14-34 років          64
35-59 років          58
60 і більше років    75
до 14 років          40
Name: alive, dtype: int64

*Бонусне завдання*         :          
Підготуй розгорнуту статистику смертності по категорії віку, класу квитка, рівню каюти та кількості родичів.      
Які фактори, на твою думку, найбільше пов'язані з рівнем смерності? (наприклад: найбільша смертність у відсотковому значенні спостерігається серед вікової групи ... класу квитка.... при наявності ... родичів та для рівня каюти.... Фактор ... має найвищий вплив на смертність)